log:
  level: "INFO"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          priority: 1000
  https:
    address: ":443"

providers:
  docker:
    network: "web"
    watch: true
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      email: "jakob.loew@thi.de"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: http
