services:
  security-science:
    image: ghcr.io/securityinmobility/security.science:latest
    restart: always
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.2g'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.security-science.rule=Host(`security.science`)"
      - "traefik.http.routers.security-science.entrypoints=https"
      - "traefik.http.routers.security-science.tls=true"
      - "traefik.http.routers.security-science.tls.certresolver=le"
      - "traefik.http.routers.security-science.middlewares=security-science-gzip"
      - "traefik.http.middlewares.security-science-gzip.compress=true"
      - "traefik.http.routers.www-security-science.rule=Host(`www.security.science`)"
      - "traefik.http.routers.www-security-science.entrypoints=https"
      - "traefik.http.routers.www-security-science.tls=true"
      - "traefik.http.routers.www-security-science.tls.certresolver=le"
      - "traefik.http.routers.www-security-science.middlewares=www-security-science-redirect"
      - "traefik.http.middlewares.www-security-science-redirect.redirectregex.regex=.*"
      - "traefik.http.middlewares.www-security-science-redirect.redirectregex.replacement=https://security.science"
      - "traefik.http.middlewares.www-security-science-redirect.redirectregex.permanent=false"

networks:
  web:
    external: true
